import type { AspectId } from "./types";

export interface AspectOption {
  id: AspectId;
  w: number;
  h: number;
  label: string;
}

export const ASPECTS: AspectOption[] = [
  { id: "1:1", w: 1, h: 1, label: "Square" },
  { id: "4:3", w: 4, h: 3, label: "4:3" },
  { id: "3:4", w: 3, h: 4, label: "3:4" },
  { id: "16:9", w: 16, h: 9, label: "16:9" },
  { id: "9:16", w: 9, h: 16, label: "9:16" },
  { id: "3:2", w: 3, h: 2, label: "3:2" },
  { id: "2:3", w: 2, h: 3, label: "2:3" },
];

export function aspectById(id: AspectId): AspectOption {
  return ASPECTS.find((a) => a.id === id)!;
}

export interface PiecePreset {
  label: string;
  cols: number;
  rows: number;
}

// Grids are picked so they follow the picture's shape and avoid awkward prime
// dimensions (no 7 x 1 style strips). Landscape grids are listed once and the
// portrait versions are generated by swapping cols and rows.
const LANDSCAPE: Record<"1:1" | "4:3" | "16:9" | "3:2", Array<[number, number]>> = {
  "1:1": [[6, 6], [8, 8], [10, 10], [14, 14], [20, 20], [30, 30]],
  "4:3": [[8, 6], [12, 9], [16, 12], [24, 18], [32, 24]],
  "16:9": [[16, 9], [20, 12], [24, 14], [32, 18]],
  "3:2": [[9, 6], [12, 8], [18, 12], [24, 16], [30, 20]],
};

const LABELS = ["Cozy", "Small", "Medium", "Large", "Big", "Huge"];

function labelIndex(count: number): number {
  if (count < 60) return 0;
  if (count < 130) return 1;
  if (count < 260) return 2;
  if (count < 450) return 3;
  if (count < 700) return 4;
  return 5;
}

export function presetsFor(aspect: AspectId): PiecePreset[] {
  const portraitOf = { "3:4": "4:3", "9:16": "16:9", "2:3": "3:2" } as const;
  const portrait = aspect in portraitOf;
  const key = (portrait ? portraitOf[aspect as keyof typeof portraitOf] : aspect) as keyof typeof LANDSCAPE;
  let prev = -1;
  return LANDSCAPE[key].map(([c, r]) => {
    // every option in a list gets its own name, even when two counts fall in the same band
    const at = Math.min(LABELS.length - 1, Math.max(labelIndex(c * r), prev + 1));
    prev = at;
    return { label: LABELS[at], cols: portrait ? r : c, rows: portrait ? c : r };
  });
}

/** The option closest to a comfortable 200 pieces. */
export function defaultPresetIndex(aspect: AspectId): number {
  const list = presetsFor(aspect);
  let best = 0;
  for (let i = 1; i < list.length; i++) {
    if (Math.abs(list[i].cols * list[i].rows - 200) < Math.abs(list[best].cols * list[best].rows - 200)) best = i;
  }
  return best;
}
