insert into words (text, category, difficulty, tags) values
  ('soccer ball', 'sports', 1, array['round', 'sports', 'small']),
  ('tennis ball', 'sports', 1, array['round', 'sports', 'small']),
  ('basketball', 'sports', 1, array['round', 'sports', 'orange']),
  ('apple', 'food', 1, array['round', 'food', 'small', 'red']),
  ('grape', 'food', 1, array['round', 'food', 'small', 'purple']),
  ('orange', 'food', 1, array['round', 'food', 'small', 'orange']),
  ('watermelon', 'food', 1, array['round', 'food', 'large', 'green']),
  ('dish washer', 'household', 2, array['appliance', 'kitchen', 'boxy']),
  ('washing machine', 'household', 2, array['appliance', 'boxy']),
  ('refrigerator', 'household', 2, array['appliance', 'kitchen', 'boxy', 'large']),
  ('umbrella', 'objects', 1, array['round', 'weather']),
  ('bicycle', 'vehicles', 2, array['wheels', 'transport']),
  ('car', 'vehicles', 1, array['wheels', 'transport']),
  ('airplane', 'vehicles', 2, array['transport', 'sky']),
  ('boat', 'vehicles', 1, array['transport', 'water']),
  ('sun', 'nature', 1, array['round', 'sky', 'yellow']),
  ('moon', 'nature', 1, array['round', 'sky']),
  ('cloud', 'nature', 1, array['sky', 'soft']),
  ('rainbow', 'nature', 2, array['sky', 'colorful']),
  ('tree', 'nature', 1, array['plant', 'tall', 'green']),
  ('flower', 'nature', 1, array['plant', 'small', 'colorful']),
  ('cactus', 'nature', 2, array['plant', 'small', 'green']),
  ('mountain', 'nature', 1, array['landscape', 'large']),
  ('giraffe', 'animals', 2, array['animal', 'tall', 'yellow']),
  ('elephant', 'animals', 1, array['animal', 'large', 'gray']),
  ('cat', 'animals', 1, array['animal', 'small', 'pet']),
  ('dog', 'animals', 1, array['animal', 'small', 'pet']),
  ('fish', 'animals', 1, array['animal', 'small', 'water']),
  ('octopus', 'animals', 2, array['animal', 'water', 'legs']),
  ('snake', 'animals', 1, array['animal', 'long']),
  ('penguin', 'animals', 1, array['animal', 'small', 'black', 'white']),
  ('spider', 'animals', 2, array['animal', 'small', 'legs']),
  ('robot', 'objects', 2, array['boxy', 'machine']),
  ('guitar', 'objects', 2, array['music', 'long']),
  ('piano', 'objects', 2, array['music', 'large', 'boxy']),
  ('clock', 'objects', 1, array['round', 'time']),
  ('camera', 'objects', 2, array['boxy', 'small']),
  ('lamp', 'objects', 1, array['household', 'tall']),
  ('chair', 'household', 1, array['furniture']),
  ('table', 'household', 1, array['furniture', 'large']),
  ('bed', 'household', 1, array['furniture', 'large']),
  ('door', 'household', 1, array['boxy', 'tall']),
  ('window', 'household', 1, array['boxy']),
  ('house', 'buildings', 1, array['boxy', 'large']),
  ('castle', 'buildings', 2, array['boxy', 'large', 'tall']),
  ('bridge', 'buildings', 2, array['large', 'long']),
  ('rocket', 'vehicles', 2, array['sky', 'tall', 'transport']),
  ('astronaut', 'people', 2, array['person', 'sky']),
  ('pirate', 'people', 2, array['person']),
  ('wizard', 'people', 2, array['person', 'tall']),
  ('king', 'people', 1, array['person']),
  ('snowman', 'seasonal', 1, array['round', 'white', 'cold']),
  ('pumpkin', 'seasonal', 1, array['round', 'orange', 'food']),
  ('ice cream', 'food', 1, array['food', 'sweet', 'cold']),
  ('pizza', 'food', 1, array['food', 'round']),
  ('hamburger', 'food', 1, array['food', 'round']),
  ('cake', 'food', 1, array['food', 'sweet']),
  ('donut', 'food', 1, array['food', 'round', 'sweet']),
  ('hot dog', 'food', 1, array['food', 'long']),
  ('taco', 'food', 2, array['food']),
  ('sushi', 'food', 2, array['food', 'small']),
  ('shoe', 'objects', 1, array['clothing', 'small']),
  ('hat', 'objects', 1, array['clothing', 'small']),
  ('crown', 'objects', 2, array['clothing', 'small']),
  ('glasses', 'objects', 1, array['clothing', 'small']),
  ('key', 'objects', 1, array['small', 'metal']),
  ('scissors', 'objects', 1, array['small', 'sharp']),
  ('book', 'objects', 1, array['boxy', 'flat']),
  ('pencil', 'objects', 1, array['long', 'small']),
  ('paintbrush', 'objects', 2, array['long', 'small']),
  ('balloon', 'objects', 1, array['round', 'colorful']),
  ('kite', 'objects', 2, array['sky', 'colorful']),
  ('anchor', 'objects', 2, array['metal', 'water']),
  ('lighthouse', 'buildings', 2, array['tall', 'water']),
  ('volcano', 'nature', 2, array['landscape', 'large', 'hot']),
  ('waterfall', 'nature', 2, array['landscape', 'water']),
  ('island', 'nature', 2, array['landscape', 'water']),
  ('dinosaur', 'animals', 2, array['animal', 'large', 'tall']),
  ('dragon', 'fantasy', 3, array['animal', 'large', 'fantasy']),
  ('unicorn', 'fantasy', 2, array['animal', 'fantasy']),
  ('ghost', 'fantasy', 1, array['fantasy', 'white']),
  ('alien', 'fantasy', 2, array['fantasy', 'green']),
  ('vampire', 'fantasy', 2, array['fantasy', 'person'])
on conflict (text) do nothing;
